[phases.setup]
nixPkgs = ["python310", "python310Packages.pip"]

[phases.install]
cmds = ["cd backend && pip install --break-system-packages -r requirements.txt"]

[phases.build]
dependsOn = ["install"]

[start]
cmd = "cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT"
