[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "gcc"]

[phases.install]
cmds = ["cd backend && pip install --break-system-packages -r requirements.txt"]

[phases.build]
cmds = ["cd backend && pip install --break-system-packages -r requirements.txt"]

[start]
cmd = "cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT"
