services:
  - type: web
    name: techyhive-backend
    env: python
    region: oregon
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        value: techyhive03@gmail.com
      - key: SMTP_PASSWORD
        value: hedqxmmsdkvteinq
      - key: SMTP_FROM_EMAIL
        value: techyhive03@gmail.com
      - key: SMTP_FROM_NAME
        value: TechyHive
